from typing import TypedDict

from langgraph.graph import StateGraph, END

from src.tools.analytics import calculate_market_metrics
from src.tools.retrieval import DocumentRetriever
from src.llm import generate_response


# ============================================================
# AGENT STATE
# ============================================================

class AgentState(TypedDict):
    """
    Shared state that moves through the LangGraph workflow.

    question:
        The user's original question.

    route:
        The route selected by the router:
        - market
        - risk
        - combined

    metrics:
        Verified market metrics calculated in Python.

    sec_context:
        Relevant SEC passages retrieved from the 10-K.

    answer:
        Final response generated by Llama 3.2.
    """

    question: str
    route: str
    metrics: dict
    sec_context: str
    answer: str


# ============================================================
# ROUTER
# ============================================================

def route_question(state: AgentState):
    """
    Decide which tools are needed based on the user's question.

    This router is deterministic.
    It does not use the LLM.
    """

    question = state["question"].lower()

    market_keywords = [
        "price",
        "return",
        "volatility",
        "moving average",
        "drawdown",
        "stock",
        "market behavior",
        "market performance",
        "performance"
    ]

    risk_keywords = [
        "risk",
        "risks",
        "competition",
        "competitor",
        "supplier",
        "suppliers",
        "supply",
        "manufacturing",
        "foundry",
        "export",
        "regulation",
        "regulatory",
        "china",
        "geopolitical",
        "sec",
        "10-k"
    ]

    needs_market = any(
        keyword in question
        for keyword in market_keywords
    )

    needs_risk = any(
        keyword in question
        for keyword in risk_keywords
    )

    if needs_market and needs_risk:
        route = "combined"

    elif needs_risk:
        route = "risk"

    else:
        route = "market"

    return {
        "route": route
    }


# ============================================================
# MARKET ANALYTICS NODE
# ============================================================

def market_node(state: AgentState):
    """
    Calculate verified market metrics using Python.

    The LLM does not calculate these values.
    """

    metrics = calculate_market_metrics(
        ticker="NVDA"
    )

    return {
        "metrics": metrics
    }


# ============================================================
# SEC RETRIEVAL NODE
# ============================================================

def risk_node(state: AgentState):
    """
    Retrieve relevant passages from NVIDIA's
    SEC 10-K Risk Factors section.
    """

    retriever = DocumentRetriever()

    retriever.index_document(
        "data/sec/nvda_10k.txt"
    )

    results = retriever.retrieve(
        query=state["question"],
        top_k=5
    )

    sec_context = "\n\n".join(
        result["text"]
        for result in results
    )

    return {
        "sec_context": sec_context
    }


# ============================================================
# LLM ANSWER NODE
# ============================================================

def answer_node(state: AgentState):
    """
    Generate the final grounded answer using Llama 3.2.

    The prompt changes depending on the route.
    """

    route = state["route"]

    # --------------------------------------------------------
    # MARKET-ONLY QUESTION
    # --------------------------------------------------------

    if route == "market":

        prompt = f"""
You are a financial market intelligence assistant.

USER QUESTION:
{state["question"]}

VERIFIED MARKET METRICS:
{state.get("metrics", {})}

Answer the user's question using ONLY
the verified market metrics above.

Rules:
- Answer every metric explicitly requested by the user.
- Do not omit requested values.
- Do not invent facts.
- Do not invent news.
- Do not use prior knowledge.
- Do not infer investor sentiment.
- Do not speculate about causes of price movement.
- Do not discuss SEC risks.
- If volatility is requested, report the supplied
  annualized_volatility_pct value.
- If return is requested, report the supplied
  return_30d_pct value.
- If moving averages are requested, use the supplied
  moving-average values and comparison fields.
- If drawdown is requested, use the supplied
  maximum_drawdown_pct value.
- Do not describe volatility as a guaranteed price range.
- Do not say the stock recovered from a drawdown unless
  recovery was explicitly calculated.
- Keep the answer concise and suitable for a business analyst.
"""

    # --------------------------------------------------------
    # RISK-ONLY QUESTION
    # --------------------------------------------------------

    elif route == "risk":

        prompt = f"""
You are a financial market intelligence assistant.

USER QUESTION:
{state["question"]}

SEC 10-K EVIDENCE:
{state.get("sec_context", "")}

Answer the user's question using ONLY
the SEC evidence provided above.

Rules:
- Mention only risks directly supported by the supplied SEC passages.
- Do not use prior knowledge.
- Do not invent facts.
- Do not invent news.
- Do not discuss stock performance.
- Do not speculate beyond the supplied evidence.
- If the evidence is insufficient, say so.
- Keep the answer concise and suitable for a business analyst.
"""

    # --------------------------------------------------------
    # COMBINED MARKET + RISK QUESTION
    # --------------------------------------------------------

    else:

        prompt = f"""
You are a financial market intelligence assistant.

USER QUESTION:
{state["question"]}

VERIFIED MARKET METRICS:
{state.get("metrics", {})}

SEC 10-K EVIDENCE:
{state.get("sec_context", "")}

Answer the user's question using ONLY
the information supplied above.

Rules:
- Answer all parts of the user's question.
- Use market metrics only for observed market behavior.
- Use SEC evidence only for business risks.
- Do not invent facts.
- Do not invent news.
- Do not use prior knowledge.
- Do not infer investor sentiment.
- Do not speculate about causes of price movement.
- Do not claim that SEC risks caused recent stock movement.
- Discuss market behavior and business risks as separate dimensions.
- Do not mention possible causes such as sentiment, market trends,
  macroeconomic conditions, or news unless they are explicitly
  provided in the evidence.
- If causation is not established, say so explicitly.
- Do not describe volatility as a guaranteed price range.
- Do not say the stock recovered from a drawdown unless
  recovery was explicitly calculated.
- If evidence is insufficient, say so.

Structure the answer as:

1. Recent market behavior
2. Main business risks
3. Overall interpretation

Keep the answer concise and suitable for a business analyst.
"""

    answer = generate_response(
        prompt
    )

    return {
        "answer": answer
    }


# ============================================================
# ROUTING HELPERS
# ============================================================

def route_after_router(state: AgentState):
    """
    Tell LangGraph which first branch to follow.
    """

    return state["route"]


def route_after_market(state: AgentState):
    """
    After market analytics:
    - market-only -> answer
    - combined -> risk retrieval
    """

    return state["route"]


# ============================================================
# BUILD LANGGRAPH AGENT
# ============================================================

def build_agent():
    """
    Build and compile the LangGraph workflow.

    Flow:

    market:
        router -> market -> answer

    risk:
        router -> risk -> answer

    combined:
        router -> market -> risk -> answer
    """

    graph = StateGraph(
        AgentState
    )

    # ------------------------
    # Add graph nodes
    # ------------------------

    graph.add_node(
        "router",
        route_question
    )

    graph.add_node(
        "market",
        market_node
    )

    graph.add_node(
        "risk",
        risk_node
    )

    graph.add_node(
        "answer",
        answer_node
    )

    # ------------------------
    # Starting point
    # ------------------------

    graph.set_entry_point(
        "router"
    )

    # ------------------------
    # Router decisions
    # ------------------------

    graph.add_conditional_edges(
        "router",
        route_after_router,
        {
            "market": "market",
            "risk": "risk",
            "combined": "market"
        }
    )

    # ------------------------
    # Market branch decisions
    # ------------------------

    graph.add_conditional_edges(
        "market",
        route_after_market,
        {
            "market": "answer",
            "combined": "risk"
        }
    )

    # ------------------------
    # Risk branch
    # ------------------------

    graph.add_edge(
        "risk",
        "answer"
    )

    # ------------------------
    # End
    # ------------------------

    graph.add_edge(
        "answer",
        END
    )

    return graph.compile()